import pandas as pd
import numpy as np

def predict_sentiment_from_satisfaction(s):
    if s >= 0.66:
        return 'positive'
    elif s <= 0.33:
        return 'negative'
    else:
        return 'neutral'

def sentiment_accuracy(user_info_df):
    """
    DEPRECATED (kept only for backward compatibility with the legacy static
    spreadsheet pipeline). This function derives the "predicted" sentiment
    label directly and deterministically from the same Satisfaction_0_1 value
    used to define the ground-truth label, which trivially inflates accuracy
    close to 100% -- the same leakage pattern flagged by Reviewer #1 (Comment 4)
    for the satisfaction metric. Use `simulate_sentiment_pipeline` for the
    revised, leakage-free simulation described in the response to reviewers.
    """
    df = user_info_df.copy()
    df['Pred_Sent'] = df['Satisfaction_0_1'].apply(predict_sentiment_from_satisfaction)
    df['Sentiment_Correct'] = (df['Pred_Sent'].str.lower() == df['Sentiment_Label'].astype(str).str.lower())
    overall = df['Sentiment_Correct'].mean()
    by_source = df.groupby('Booking_Source').Sentiment_Correct.mean().reset_index().rename(columns={'Sentiment_Correct':'sentiment_accuracy'})
    return overall, by_source


def true_sentiment_label(true_satisfaction: float) -> str:
    """Ground-truth sentiment implied by the (independently generated) true satisfaction."""
    if true_satisfaction >= 0.66:
        return 'positive'
    elif true_satisfaction <= 0.33:
        return 'negative'
    return 'neutral'


def simulate_sentiment_pipeline(interactions: pd.DataFrame, seed: int = 0, model_accuracy: float = 0.85) -> pd.DataFrame:
    """
    Leakage-free replacement for `sentiment_accuracy`, used with the revised
    simulation pipeline (src/data_generation.py). Ground-truth sentiment is derived
    from `true_satisfaction` (the evaluation-time signal, independent of any
    recommender's estimates). A simulated sentiment-classifier prediction is then
    generated by injecting label noise at rate (1 - model_accuracy) from an
    INDEPENDENT random stream, mimicking a realistic imperfect text classifier
    instead of copying the ground-truth label back as the "prediction".

    Returns a DataFrame with True_Sentiment, Pred_Sentiment, and a boolean
    Sentiment_Correct column whose mean now reflects a realistic classifier
    accuracy (~model_accuracy) rather than a trivially perfect one.
    """
    rng = np.random.default_rng(seed + 5000)
    labels = ['positive', 'neutral', 'negative']
    df = interactions.copy()
    df['True_Sentiment'] = df['true_satisfaction'].apply(true_sentiment_label)

    preds = []
    for true_label in df['True_Sentiment']:
        if rng.random() < model_accuracy:
            preds.append(true_label)
        else:
            wrong_options = [l for l in labels if l != true_label]
            preds.append(rng.choice(wrong_options))
    df['Pred_Sentiment'] = preds
    df['Sentiment_Correct'] = df['True_Sentiment'] == df['Pred_Sentiment']
    return df


if __name__ == '__main__':
    print('Sentiment utilities loaded')
